### ISSUE TITLE
보드 리스트 버튼

### ISSUE THREAD

**Issue by ofleaf** [redgoose-dev/checker-board#4]
보드 리스트 버튼을 클릭 했을 때 보여지는 모달 창이 처음엔 오늘 날짜 하루만 나와서 무엇을 하는 모달 창인지 이해가 좀 안되었습니다
보드의 히스토리를 보여주는 모달인 것 같은데 그게 맞다면 추가로 해당 일자에 진행률도 표시된다면 좋을 것 같네요

**Comment by redgoose-dev** [comment]
@ofleaf 말씀하시던 목록은 히스토리가 맞습니다. 과거의 내용을 열람할 수 있는 장치인 것이죠.
진행률을 목록에 표시하는것은 좋은 아이디어네요.
만약 넣게 된다면 퍼센테이지 필드로 빼야할거 같아 보이는데 고민 좀 해보겠습니다 :)

**Comment by redgoose-dev** [comment]
@ofleaf 목록에 퍼센트 적용해봤습니다.
왠만하면 건드리기 싫었던 db필드가 추가되어서 처음 접속하면 오류가 나고 그럴수도 있으니 다음과 같이 대비를 할 수 있을겁니다.

1. 설정 -> 데이터 백업
2. 브라우저 캐시 비우면서 새로고침
3. 설정 -> 데이터 복원

업그레이드 기능을 추가해봤지만 혹시나 싶어 작동이 제대로 안될수도 있습니다.
